### ISSUE TITLE
Ideas on Front-End

### ISSUE THREAD

**Issue by puffinism** [Ajeeth-Abhijit-Collaboration-Group/Entrar-Cliend-End#1]
**So basically we don't want to rip off entrar completely, so here you can post your ideas about the front-end also I know a bit of JS and therefore I can help you with it too.**

## Few ideas I have

- So being students we know that "online class" as what we call is not fully interactive and is boring a few ways of making it interactive is by making a chat system somewhat like discord but integrated into the platform so that you don't have to look at WhatsApp and can fully use the integrated one.
- The second one is the assignment tab, **_gamifying_** it to allow more concentration towards studies, gamifying is one of the key elements in keeping the studies interesting since kids and teens are attracted to games, and also a rewarding system would make students submit the assignments as soon as possible and the rewards vary depending on the time you submit.
- Obviously, rewards need to be used or there won't be any point in rewarding, therefore a virtual store would be great for students to redeem their points or the virtual currency to get costumes and badges and extra bonuses in chat like allowing GIFs in PFP's and also unlocking many other things such as the banner and private chat during classroom (Private chat will be monitored to and can be disabled by the teachers so that no student gets bullied and inappropriate things are not sent. ). 
- [Habitica](https://habitica.com/) is an open-source task manager that rewards users for completing their tasks and with this reward the users can buy costumes, so we can develop something like this and integrate it with the assignments so that when an assignment is created it will be automatically will be added to the task manager and completing it will reward you and with rewards, you can buy **_chat perks_** or **_costumes_**.
- A leveling up system that will give you bonuses and perks, to keep the students motivated in completing the assignments also the students will be able to view other students' levels including their friends, and also a weekly scoreboard will be placed to show who gained the highest XP in the grade.
- A quiz maker, so that teachers can create their own quiz and later have a quiz in the class somewhat like quizizz but integrated to the platform, also the students will be allowed to make quiz but will have to be a certain level.

**Comment by puffinism** [comment]
[Source code for habitica](https://github.com/HabitRPG/habitica) It's mostly made of JS and CSS so it will be easy to understand.

**Comment by Liftoff-Studios** [comment]
Hmm, sounds good. But first we need to implement the core functionality to add remove and modify assignments
That's the main thing
then we can work on other features

**Comment by puffinism** [comment]
> Hmm, sounds good. But first we need to implement the core functionality to add remove and modify assignments That's the main thing then we can work on other features

Yeah exactly just forgot to mention that, we will work on core functionality and later add the features.

**Comment by Liftoff-Studios** [comment]
Also first we have to make the front-end and then the backend

I recently tried to make something the other war around and it went terribly wrong XD

**Comment by puffinism** [comment]
> Also first we have to make the front-end and then the backend
> 
> I recently tried to make something the other war around and it went terribly wrong XD

ah.. yeah when I was working with my father in making static pages he said that while making dynamic pages the front end has to be made first since once the backend is made any changes done to the front end has to be also done to the back (Like the input and other requests) and will be a pain a lot of pain. Also if you make the backend first then making changes to the frontend will become hard and will once again have to configure the back if there is a slight difference.

**Comment by puffinism** [comment]
Yeah, we can start with the front then.

**Comment by puffinism** [comment]
Can you give an idea of how the Front-end would look?

**Comment by Liftoff-Studios** [comment]
Still thinking about it

**Comment by puffinism** [comment]
> Still thinking about it

Also for the login page, I recommend having RES encryption and also putting random characters in the password and encrypting it. So for example if the password is 'Password@1234' then the program inputs random characters and makes it like 'Pas!sw@dos#rd@12s34' and remembers the characters placed with a position and even this is encrypted using tr with multiple 
encryption so that in **_case someone hacks there is no password breach_**.

**Comment by Liftoff-Studios** [comment]
I don't think we need password encryption as long as we use https:// domains

**Comment by Liftoff-Studios** [comment]
https:// domains will encrypt any information sent to and from the server

**Comment by puffinism** [comment]
> https:// domains will encrypt any information sent to and from the server

Yeah but if they targetted the DB then that would be a problem having a proxy or something is good instead of encryption then. Since direct connection with servers is not really good if we got some pro hacker then we would get hacked easily

**Comment by Liftoff-Studios** [comment]
we can see about it later

**Comment by Liftoff-Studios** [comment]
Hey ajeeth
This is where my work has reached so far
https://entrar-in-rust.liftoff-ka.repl.co/login.html

**Comment by Liftoff-Studios** [comment]
I started working on it today for like 15 mins
we have exams so i didn't work on this much

**Comment by puffinism** [comment]
Yeah I get it I am just spending 1hr a day, rest of the time i am just practicing for the exams

**Comment by ajeethbt** [comment]
> I started working on it today for like 15 mins we have exams so i didn't work on this much

Where is the source code?
